version: '3.8'
name: zero2prod

services:
  db:
    image: postgres:15
    container_name: zero2prod_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=zero2prod
      - POSTGRES_PASSWORD=zero2prod_password
      - POSTGRES_DB=newsletter
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - main_net

volumes:
  pg_data:

networks:
  main_net:
