application:
  host: "127.0.0.1"
  port: 8080
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "http://localhost"
  sender_email: "test@example.com"
  authorization_token: "my-super-secret-token"